### ISSUE TITLE
This still work with ah.nl?

### ISSUE THREAD

**Issue by ualex73** [RinseV/albert-heijn-wrapper#6]
I tested it quickly, but I got a HTTP/400.

**Comment by RinseV** [comment]
Seems AH added a new header to every app request that is needed for the request to work, I've now added this header to the wrapper so the requests should work again.

**Comment by ualex73** [comment]
Thanks!

**Comment by DotwoodMedia** [comment]
I tried this and got the following error:
Unhandled promise rejection: Error: undefined: [object Object]
