### ISSUE TITLE
Returns undefined

### ISSUE THREAD

**Issue by DotwoodMedia** [RinseV/albert-heijn-wrapper#9]
I tried this and got the following error:
`Unhandled promise rejection: Error: undefined: [object Object]`

**Comment by RinseV** [comment]
Could you provide some more info? What function did you run? Can you show me the code you used? Could you stringify the result (```JSON.stringify(result)```) to give some more error information?

**Comment by DotwoodMedia** [comment]
I run the following function:
`const ah = new AH();

        const filter = {
            brand: "AH Glutenvrij",
            property: [ProductPropertyFilter.GlutenFree, ProductPropertyFilter.Vegan]
        };
        const products = await ah.product().getProductsFromName("Brood", {
            filter,
            sort: ProductSortOptions.PriceAsc
        });
        
        const res = products.products.map((product) => {
            return product.title;
        });
        console.log(res);`

I only use this in react native so don't know if that could be a problem haha

**Comment by RinseV** [comment]
Running this code does not seem to give any errors by just running it in node (LTS 16.17.0) for me. Did you try to stringify the ``[object Object]`` and see what it says? It could be an issue with React native, though that would be strange.
